baseURL = "https://blog.willowpatchgames.com"
languageCode = "en-us"
title = "Blog @ Willow Patch Games"
paginate = 6
theme = "hugo-theme-novela"

[social]
twitter = "https://twitter.com/willowpatchgame"
website = "https://willowpatchgames.com"

[taxonomies]
author = "authors"
